from tkinter import *


window = Tk()
window.title('WitherBot')
window.geometry('300x400')
btn = Button(window, text = '    1    ')
btn.grid(column = 0, row = 1)
btn = Button(window, text = '    2    ')
btn.grid(column = 1, row = 1)
btn = Button(window, text = '    3    ')
btn.grid(column = 2, row = 1)
btn = Button(window, text = '    4    ')
btn.grid(column = 0, row = 2)
btn = Button(window, text = '    5    ')
btn.grid(column = 1, row = 2)
btn = Button(window, text = '    6    ')
btn.grid(column = 2, row = 2)
btn = Button(window, text = '    7    ')
btn.grid(column = 0, row = 3)
btn = Button(window, text = '    8    ')
btn.grid(column = 1, row = 3)
btn = Button(window, text = '    9    ')
btn.grid(column = 2, row = 3)
btn = Button(window, text = '+')
btn.grid(column = 3, row = 3)
btn = Button(window, text = '-')
btn.grid(column = 4, row = 3)
btn = Button(window, text = '*')
btn.grid(column = 5, row = 3)
btn = Button(window, text = '/')
btn.grid(column = 6, row = 3)
btn = Button(window, text = '=')
btn.grid(column = 7, row = 3)
btn = Button(window, text = '^')
btn.grid(column = 8, row = 3)



window.mainloop()
